export const SMS_PRICING = [
  {
    country: "Afghanistan",
    messagebird_cost_gbp: "0.255",
    gbp_price: "0.509",
    usd_price: "0.666",
    is_range: false,
    priority: -1,
  },
  {
    country: "Albania",
    messagebird_cost_gbp: "0.066",
    gbp_price: "0.131",
    usd_price: "0.171",
    is_range: false,
    priority: -1,
  },
  {
    country: "Algeria",
    messagebird_cost_gbp: "0.195",
    gbp_price: "0.390",
    usd_price: "0.510",
    is_range: false,
    priority: -1,
  },
  {
    country: "American Samoa",
    messagebird_cost_gbp: "0.135",
    gbp_price: "0.269",
    usd_price: "0.352",
    is_range: false,
    priority: -1,
  },
  {
    country: "Andorra",
    messagebird_cost_gbp: "0.095",
    gbp_price: "0.189",
    usd_price: "0.248",
    is_range: false,
    priority: -1,
  },
  {
    country: "Angola",
    messagebird_cost_gbp: "0.067",
    gbp_price: "0.134",
    usd_price: "0.176",
    is_range: false,
    priority: -1,
  },
  {
    country: "Anguilla",
    messagebird_cost_gbp: "0.100",
    gbp_price: "0.200",
    usd_price: "0.262",
    is_range: false,
    priority: -1,
  },
  {
    country: "Antigua and Barbuda",
    messagebird_cost_gbp: "0.075",
    gbp_price: "0.150",
    usd_price: "0.196",
    is_range: false,
    priority: -1,
  },
  {
    country: "Argentina",
    messagebird_cost_gbp: "0.065",
    gbp_price: "0.131",
    usd_price: "0.171",
    is_range: false,
    priority: -1,
  },
  {
    country: "Armenia",
    messagebird_cost_gbp: "0.105",
    gbp_price: "0.209",
    usd_price: "0.274",
    is_range: false,
    priority: -1,
  },
  {
    country: "Aruba",
    messagebird_cost_gbp: "0.119",
    gbp_price: "0.238",
    usd_price: "0.312",
    is_range: false,
    priority: -1,
  },
  {
    country: "Australia",
    messagebird_cost_gbp: "0.014",
    gbp_price: "0.029",
    usd_price: "0.038",
    is_range: false,
    priority: 3,
  },
  {
    country: "Austria",
    messagebird_cost_gbp: "0.070",
    gbp_price: "0.140",
    usd_price: "0.183",
    is_range: false,
    priority: -1,
  },
  {
    country: "Azerbaijan",
    messagebird_cost_gbp: "0.277",
    gbp_price: "0.555",
    usd_price: "0.726",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bahamas",
    messagebird_cost_gbp: "0.037",
    gbp_price: "0.075",
    usd_price: "0.098",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bahrain",
    messagebird_cost_gbp: "0.027",
    gbp_price: "0.055",
    usd_price: "0.071",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bangladesh",
    messagebird_cost_gbp: "0.229",
    gbp_price: "0.457",
    usd_price: "0.598",
    is_range: false,
    priority: -1,
  },
  {
    country: "Barbados",
    messagebird_cost_gbp: "0.101",
    gbp_price: "0.202",
    usd_price: "0.265",
    is_range: false,
    priority: -1,
  },
  {
    country: "Belarus",
    messagebird_cost_gbp: "0.179",
    gbp_price: "0.358",
    usd_price: "0.469",
    is_range: false,
    priority: -1,
  },
  {
    country: "Belgium",
    messagebird_cost_gbp: "0.069",
    gbp_price: "0.138",
    usd_price: "0.181",
    is_range: false,
    priority: -1,
  },
  {
    country: "Belize",
    messagebird_cost_gbp: "0.207",
    gbp_price: "0.414",
    usd_price: "0.542",
    is_range: false,
    priority: -1,
  },
  {
    country: "Benin",
    messagebird_cost_gbp: "0.108",
    gbp_price: "0.216",
    usd_price: "0.283",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bermuda",
    messagebird_cost_gbp: "0.130",
    gbp_price: "0.260",
    usd_price: "0.341",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bhutan",
    messagebird_cost_gbp: "0.282",
    gbp_price: "0.565",
    usd_price: "0.739",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bolivia",
    messagebird_cost_gbp: "0.104",
    gbp_price: "0.208",
    usd_price: "0.272",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bosnia and Herzegovina",
    messagebird_cost_gbp: "0.060",
    gbp_price: "0.120",
    usd_price: "0.157",
    is_range: false,
    priority: -1,
  },
  {
    country: "Botswana",
    messagebird_cost_gbp: "0.071",
    gbp_price: "0.143",
    usd_price: "0.187",
    is_range: false,
    priority: -1,
  },
  {
    country: "Brazil",
    messagebird_cost_gbp: "0.043",
    gbp_price: "0.086",
    usd_price: "0.112",
    is_range: false,
    priority: -1,
  },
  {
    country: "British Virgin Islands",
    messagebird_cost_gbp: "0.139",
    gbp_price: "0.278",
    usd_price: "0.363",
    is_range: false,
    priority: -1,
  },
  {
    country: "Brunei Darussalam",
    messagebird_cost_gbp: "0.014",
    gbp_price: "0.029",
    usd_price: "0.037",
    is_range: false,
    priority: -1,
  },
  {
    country: "Bulgaria",
    messagebird_cost_gbp: "0.104",
    gbp_price: "0.208",
    usd_price: "0.273",
    is_range: false,
    priority: -1,
  },
  {
    country: "Burkina Faso",
    messagebird_cost_gbp: "0.127",
    gbp_price: "0.255",
    usd_price: "0.333",
    is_range: false,
    priority: -1,
  },
  {
    country: "Burundi",
    messagebird_cost_gbp: "0.269",
    gbp_price: "0.538",
    usd_price: "0.703",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cabo Verde",
    messagebird_cost_gbp: "0.157",
    gbp_price: "0.315",
    usd_price: "0.412",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cambodia",
    messagebird_cost_gbp: "0.147",
    gbp_price: "0.295",
    usd_price: "0.386",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cameroon",
    messagebird_cost_gbp: "0.108",
    gbp_price: "0.216",
    usd_price: "0.283",
    is_range: false,
    priority: -1,
  },
  {
    country: "Canada",
    messagebird_cost_gbp: "0.003",
    gbp_price: "0.006",
    usd_price: "0.008",
    is_range: false,
    priority: 1,
  },
  {
    country: "Cayman Islands",
    messagebird_cost_gbp: "0.118",
    gbp_price: "0.236",
    usd_price: "0.309",
    is_range: false,
    priority: -1,
  },
  {
    country: "Central African Republic",
    messagebird_cost_gbp: "0.087",
    gbp_price: "0.174",
    usd_price: "0.228",
    is_range: false,
    priority: -1,
  },
  {
    country: "Chad",
    messagebird_cost_gbp: "0.207",
    gbp_price: "0.414",
    usd_price: "0.542",
    is_range: false,
    priority: -1,
  },
  {
    country: "Chile",
    messagebird_cost_gbp: "0.047",
    gbp_price: "0.093",
    usd_price: "0.122",
    is_range: false,
    priority: -1,
  },
  {
    country: "China",
    messagebird_cost_gbp: "0.026",
    gbp_price: "0.052",
    usd_price: "0.069",
    is_range: false,
    priority: -1,
  },
  {
    country: "Colombia",
    messagebird_cost_gbp: "0.037",
    gbp_price: "0.075",
    usd_price: "0.098",
    is_range: false,
    priority: -1,
  },
  {
    country: "Comoros",
    messagebird_cost_gbp: "0.222",
    gbp_price: "0.443",
    usd_price: "0.580",
    is_range: false,
    priority: -1,
  },
  {
    country: "Congo",
    messagebird_cost_gbp: "0.148",
    gbp_price: "0.296",
    usd_price: "0.387",
    is_range: false,
    priority: -1,
  },
  {
    country: "Congo Democratic Republic",
    messagebird_cost_gbp: "0.136",
    gbp_price: "0.271",
    usd_price: "0.355",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cook Islands",
    messagebird_cost_gbp: "0.100",
    gbp_price: "0.200",
    usd_price: "0.261",
    is_range: false,
    priority: -1,
  },
  {
    country: "Costa Rica",
    messagebird_cost_gbp: "0.029",
    gbp_price: "0.059",
    usd_price: "0.077",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cote D'Ivoire",
    messagebird_cost_gbp: "0.179",
    gbp_price: "0.358",
    usd_price: "0.469",
    is_range: false,
    priority: -1,
  },
  {
    country: "Croatia",
    messagebird_cost_gbp: "0.066",
    gbp_price: "0.131",
    usd_price: "0.171",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cuba",
    messagebird_cost_gbp: "0.060",
    gbp_price: "0.120",
    usd_price: "0.157",
    is_range: false,
    priority: -1,
  },
  {
    country: "Cyprus",
    messagebird_cost_gbp: "0.062",
    gbp_price: "0.124",
    usd_price: "0.162",
    is_range: false,
    priority: -1,
  },
  {
    country: "Czech Republic",
    messagebird_cost_gbp: "0.043",
    gbp_price: "0.086",
    usd_price: "0.113",
    is_range: false,
    priority: -1,
  },
  {
    country: "Denmark",
    messagebird_cost_gbp: "0.040",
    gbp_price: "0.079",
    usd_price: "0.104",
    is_range: false,
    priority: -1,
  },
  {
    country: "Djibouti",
    messagebird_cost_gbp: "0.116",
    gbp_price: "0.232",
    usd_price: "0.304",
    is_range: false,
    priority: -1,
  },
  {
    country: "Dominica",
    messagebird_cost_gbp: "0.122",
    gbp_price: "0.244",
    usd_price: "0.319",
    is_range: false,
    priority: -1,
  },
  {
    country: "Dominican Republic",
    messagebird_cost_gbp: "0.057",
    gbp_price: "0.114",
    usd_price: "0.149",
    is_range: false,
    priority: -1,
  },
  {
    country: "Ecuador",
    messagebird_cost_gbp: "0.137",
    gbp_price: "0.274",
    usd_price: "0.358",
    is_range: false,
    priority: -1,
  },
  {
    country: "Egypt",
    messagebird_cost_gbp: "0.204",
    gbp_price: "0.408",
    usd_price: "0.534",
    is_range: false,
    priority: -1,
  },
  {
    country: "El Salvador",
    messagebird_cost_gbp: "0.071",
    gbp_price: "0.143",
    usd_price: "0.187",
    is_range: false,
    priority: -1,
  },
  {
    country: "Equatorial Guinea",
    messagebird_cost_gbp: "0.124",
    gbp_price: "0.247",
    usd_price: "0.324",
    is_range: false,
    priority: -1,
  },
  {
    country: "Eritrea",
    messagebird_cost_gbp: "0.087",
    gbp_price: "0.173",
    usd_price: "0.227",
    is_range: false,
    priority: -1,
  },
  {
    country: "Estonia",
    messagebird_cost_gbp: "0.069",
    gbp_price: "0.137",
    usd_price: "0.179",
    is_range: false,
    priority: -1,
  },
  {
    country: "Eswatini",
    messagebird_cost_gbp: "0.068",
    gbp_price: "0.135",
    usd_price: "0.177",
    is_range: false,
    priority: -1,
  },
  {
    country: "Ethiopia",
    messagebird_cost_gbp: "0.245",
    gbp_price: "0.490",
    usd_price: "0.641",
    is_range: false,
    priority: -1,
  },
  {
    country: "Faeroe Islands",
    messagebird_cost_gbp: "0.050",
    gbp_price: "0.100",
    usd_price: "0.130",
    is_range: false,
    priority: -1,
  },
  {
    country: "Falkland Islands",
    messagebird_cost_gbp: "0.052",
    gbp_price: "0.103",
    usd_price: "0.135",
    is_range: false,
    priority: -1,
  },
  {
    country: "Fiji",
    messagebird_cost_gbp: "0.116",
    gbp_price: "0.233",
    usd_price: "0.304",
    is_range: false,
    priority: -1,
  },
  {
    country: "Finland",
    messagebird_cost_gbp: "0.062",
    gbp_price: "0.123",
    usd_price: "0.161",
    is_range: false,
    priority: -1,
  },
  {
    country: "France",
    messagebird_cost_gbp: "0.057",
    gbp_price: "0.114",
    usd_price: "0.149",
    is_range: false,
    priority: -1,
  },
  {
    country: "French Guiana",
    messagebird_cost_gbp: "0.068",
    gbp_price: "0.135",
    usd_price: "0.177",
    is_range: false,
    priority: -1,
  },
  {
    country: "French Polynesia",
    messagebird_cost_gbp: "0.129",
    gbp_price: "0.257",
    usd_price: "0.336",
    is_range: false,
    priority: -1,
  },
  {
    country: "Gabon",
    messagebird_cost_gbp: "0.188",
    gbp_price: "0.377",
    usd_price: "0.493",
    is_range: false,
    priority: -1,
  },
  {
    country: "Gambia",
    messagebird_cost_gbp: "0.119",
    gbp_price: "0.237",
    usd_price: "0.311",
    is_range: false,
    priority: -1,
  },
  {
    country: "Georgia",
    messagebird_cost_gbp: "0.120",
    gbp_price: "0.241",
    usd_price: "0.315",
    is_range: false,
    priority: -1,
  },
  {
    country: "Germany",
    messagebird_cost_gbp: "0.071",
    gbp_price: "0.142",
    usd_price: "0.186",
    is_range: false,
    priority: -1,
  },
  {
    country: "Ghana",
    messagebird_cost_gbp: "0.139",
    gbp_price: "0.278",
    usd_price: "0.364",
    is_range: false,
    priority: -1,
  },
  {
    country: "Gibraltar",
    messagebird_cost_gbp: "0.079",
    gbp_price: "0.157",
    usd_price: "0.205",
    is_range: false,
    priority: -1,
  },
  {
    country: "Greece",
    messagebird_cost_gbp: "0.044",
    gbp_price: "0.089",
    usd_price: "0.116",
    is_range: false,
    priority: -1,
  },
  {
    country: "Greenland",
    messagebird_cost_gbp: "0.029",
    gbp_price: "0.059",
    usd_price: "0.077",
    is_range: false,
    priority: -1,
  },
  {
    country: "Grenada",
    messagebird_cost_gbp: "0.135",
    gbp_price: "0.270",
    usd_price: "0.354",
    is_range: false,
    priority: -1,
  },
  {
    country: "Guatemala",
    messagebird_cost_gbp: "0.141",
    gbp_price: "0.282",
    usd_price: "0.369",
    is_range: false,
    priority: -1,
  },
  {
    country: "Guinea",
    messagebird_cost_gbp: "0.108",
    gbp_price: "0.217",
    usd_price: "0.284",
    is_range: false,
    priority: -1,
  },
  {
    country: "Guinea-Bissau",
    messagebird_cost_gbp: "0.130",
    gbp_price: "0.260",
    usd_price: "0.340",
    is_range: false,
    priority: -1,
  },
  {
    country: "Guyana",
    messagebird_cost_gbp: "0.128",
    gbp_price: "0.256",
    usd_price: "0.334",
    is_range: false,
    priority: -1,
  },
  {
    country: "Haiti",
    messagebird_cost_gbp: "0.166",
    gbp_price: "0.332",
    usd_price: "0.434",
    is_range: false,
    priority: -1,
  },
  {
    country: "Honduras",
    messagebird_cost_gbp: "0.103",
    gbp_price: "0.205",
    usd_price: "0.269",
    is_range: false,
    priority: -1,
  },
  {
    country: "Hong Kong",
    messagebird_cost_gbp: "0.051",
    gbp_price: "0.101",
    usd_price: "0.133",
    is_range: false,
    priority: -1,
  },
  {
    country: "Hungary",
    messagebird_cost_gbp: "0.065",
    gbp_price: "0.130",
    usd_price: "0.170",
    is_range: false,
    priority: -1,
  },
  {
    country: "Iceland",
    messagebird_cost_gbp: "0.050",
    gbp_price: "0.100",
    usd_price: "0.131",
    is_range: false,
    priority: -1,
  },
  {
    country: "India",
    messagebird_cost_gbp: "0.058",
    gbp_price: "0.117",
    usd_price: "0.153",
    is_range: false,
    priority: -1,
  },
  {
    country: "Indonesia",
    messagebird_cost_gbp: "0.310",
    gbp_price: "0.620",
    usd_price: "0.811",
    is_range: false,
    priority: -1,
  },
  {
    country: "Iran",
    messagebird_cost_gbp: "0.247",
    gbp_price: "0.495",
    usd_price: "0.648",
    is_range: false,
    priority: -1,
  },
  {
    country: "Iraq",
    messagebird_cost_gbp: "0.243",
    gbp_price: "0.487",
    usd_price: "0.637",
    is_range: false,
    priority: -1,
  },
  {
    country: "Ireland",
    messagebird_cost_gbp: "0.052",
    gbp_price: "0.105",
    usd_price: "0.137",
    is_range: false,
    priority: -1,
  },
  {
    country: "Israel",
    messagebird_cost_gbp: "0.128 - 0.247",
    gbp_price: "0.256 - 0.494",
    usd_price: "0.335 - 0.647",
    is_range: true,
    priority: -1,
  },
  {
    country: "Italy",
    messagebird_cost_gbp: "0.066",
    gbp_price: "0.133",
    usd_price: "0.173",
    is_range: false,
    priority: -1,
  },
  {
    country: "Jamaica",
    messagebird_cost_gbp: "0.145",
    gbp_price: "0.291",
    usd_price: "0.380",
    is_range: false,
    priority: -1,
  },
  {
    country: "Japan",
    messagebird_cost_gbp: "0.057",
    gbp_price: "0.113",
    usd_price: "0.148",
    is_range: false,
    priority: -1,
  },
  {
    country: "Jordan",
    messagebird_cost_gbp: "0.192",
    gbp_price: "0.383",
    usd_price: "0.501",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kazakhstan",
    messagebird_cost_gbp: "0.203",
    gbp_price: "0.405",
    usd_price: "0.530",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kenya",
    messagebird_cost_gbp: "0.096",
    gbp_price: "0.192",
    usd_price: "0.251",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kiribati",
    messagebird_cost_gbp: "0.104",
    gbp_price: "0.208",
    usd_price: "0.272",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kosovo",
    messagebird_cost_gbp: "0.146",
    gbp_price: "0.292",
    usd_price: "0.382",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kuwait",
    messagebird_cost_gbp: "0.185",
    gbp_price: "0.369",
    usd_price: "0.483",
    is_range: false,
    priority: -1,
  },
  {
    country: "Kyrgyz Republic",
    messagebird_cost_gbp: "0.227",
    gbp_price: "0.455",
    usd_price: "0.595",
    is_range: false,
    priority: -1,
  },
  {
    country: "Lao People's Democratic Republic",
    messagebird_cost_gbp: "0.129",
    gbp_price: "0.259",
    usd_price: "0.339",
    is_range: false,
    priority: -1,
  },
  {
    country: "Latvia",
    messagebird_cost_gbp: "0.047",
    gbp_price: "0.095",
    usd_price: "0.124",
    is_range: false,
    priority: -1,
  },
  {
    country: "Lebanon",
    messagebird_cost_gbp: "0.196",
    gbp_price: "0.392",
    usd_price: "0.513",
    is_range: false,
    priority: -1,
  },
  {
    country: "Lesotho",
    messagebird_cost_gbp: "0.150",
    gbp_price: "0.300",
    usd_price: "0.393",
    is_range: false,
    priority: -1,
  },
  {
    country: "Liberia",
    messagebird_cost_gbp: "0.105",
    gbp_price: "0.209",
    usd_price: "0.274",
    is_range: false,
    priority: -1,
  },
  {
    country: "Libya",
    messagebird_cost_gbp: "0.283",
    gbp_price: "0.566",
    usd_price: "0.741",
    is_range: false,
    priority: -1,
  },
  {
    country: "Liechtenstein",
    messagebird_cost_gbp: "0.025",
    gbp_price: "0.050",
    usd_price: "0.066",
    is_range: false,
    priority: -1,
  },
  {
    country: "Lithuania",
    messagebird_cost_gbp: "0.041",
    gbp_price: "0.082",
    usd_price: "0.108",
    is_range: false,
    priority: -1,
  },
  {
    country: "Luxembourg",
    messagebird_cost_gbp: "0.054",
    gbp_price: "0.109",
    usd_price: "0.142",
    is_range: false,
    priority: -1,
  },
  {
    country: "Macao",
    messagebird_cost_gbp: "0.042",
    gbp_price: "0.084",
    usd_price: "0.110",
    is_range: false,
    priority: -1,
  },
  {
    country: "Madagascar",
    messagebird_cost_gbp: "0.282",
    gbp_price: "0.564",
    usd_price: "0.738",
    is_range: false,
    priority: -1,
  },
  {
    country: "Malawi",
    messagebird_cost_gbp: "0.189",
    gbp_price: "0.378",
    usd_price: "0.495",
    is_range: false,
    priority: -1,
  },
  {
    country: "Malaysia",
    messagebird_cost_gbp: "0.148",
    gbp_price: "0.297",
    usd_price: "0.388",
    is_range: false,
    priority: -1,
  },
  {
    country: "Maldives",
    messagebird_cost_gbp: "0.126",
    gbp_price: "0.252",
    usd_price: "0.329",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mali",
    messagebird_cost_gbp: "0.164",
    gbp_price: "0.328",
    usd_price: "0.429",
    is_range: false,
    priority: -1,
  },
  {
    country: "Malta",
    messagebird_cost_gbp: "0.049",
    gbp_price: "0.098",
    usd_price: "0.128",
    is_range: false,
    priority: -1,
  },
  {
    country: "Marshall Islands",
    messagebird_cost_gbp: "0.120",
    gbp_price: "0.240",
    usd_price: "0.314",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mauritania",
    messagebird_cost_gbp: "0.185",
    gbp_price: "0.370",
    usd_price: "0.484",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mauritius",
    messagebird_cost_gbp: "0.121",
    gbp_price: "0.242",
    usd_price: "0.316",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mexico",
    messagebird_cost_gbp: "0.077",
    gbp_price: "0.154",
    usd_price: "0.202",
    is_range: false,
    priority: -1,
  },
  {
    country: "Micronesia",
    messagebird_cost_gbp: "0.054",
    gbp_price: "0.109",
    usd_price: "0.143",
    is_range: false,
    priority: -1,
  },
  {
    country: "Moldova",
    messagebird_cost_gbp: "0.051",
    gbp_price: "0.103",
    usd_price: "0.134",
    is_range: false,
    priority: -1,
  },
  {
    country: "Monaco",
    messagebird_cost_gbp: "0.133",
    gbp_price: "0.266",
    usd_price: "0.347",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mongolia",
    messagebird_cost_gbp: "0.197",
    gbp_price: "0.393",
    usd_price: "0.514",
    is_range: false,
    priority: -1,
  },
  {
    country: "Montenegro",
    messagebird_cost_gbp: "0.081",
    gbp_price: "0.163",
    usd_price: "0.213",
    is_range: false,
    priority: -1,
  },
  {
    country: "Montserrat",
    messagebird_cost_gbp: "0.093",
    gbp_price: "0.187",
    usd_price: "0.244",
    is_range: false,
    priority: -1,
  },
  {
    country: "Morocco",
    messagebird_cost_gbp: "0.157",
    gbp_price: "0.314",
    usd_price: "0.411",
    is_range: false,
    priority: -1,
  },
  {
    country: "Mozambique",
    messagebird_cost_gbp: "0.133",
    gbp_price: "0.265",
    usd_price: "0.347",
    is_range: false,
    priority: -1,
  },
  {
    country: "Myanmar",
    messagebird_cost_gbp: "0.201",
    gbp_price: "0.402",
    usd_price: "0.526",
    is_range: false,
    priority: -1,
  },
  {
    country: "Namibia",
    messagebird_cost_gbp: "0.045",
    gbp_price: "0.090",
    usd_price: "0.117",
    is_range: false,
    priority: -1,
  },
  {
    country: "Nauru",
    messagebird_cost_gbp: "0.157",
    gbp_price: "0.313",
    usd_price: "0.410",
    is_range: false,
    priority: -1,
  },
  {
    country: "Nepal",
    messagebird_cost_gbp: "0.157",
    gbp_price: "0.314",
    usd_price: "0.410",
    is_range: false,
    priority: -1,
  },
  {
    country: "Netherlands",
    messagebird_cost_gbp: "0.069",
    gbp_price: "0.138",
    usd_price: "0.181",
    is_range: false,
    priority: -1,
  },
  {
    country: "Netherlands Antilles (dissolved)",
    messagebird_cost_gbp: "0.089",
    gbp_price: "0.178",
    usd_price: "0.233",
    is_range: false,
    priority: -1,
  },
  {
    country: "New Caledonia",
    messagebird_cost_gbp: "0.126",
    gbp_price: "0.252",
    usd_price: "0.330",
    is_range: false,
    priority: -1,
  },
  {
    country: "New Zealand",
    messagebird_cost_gbp: "0.075",
    gbp_price: "0.150",
    usd_price: "0.197",
    is_range: false,
    priority: -1,
  },
  {
    country: "Nicaragua",
    messagebird_cost_gbp: "0.062",
    gbp_price: "0.124",
    usd_price: "0.162",
    is_range: false,
    priority: -1,
  },
  {
    country: "Niger",
    messagebird_cost_gbp: "0.218",
    gbp_price: "0.435",
    usd_price: "0.570",
    is_range: false,
    priority: -1,
  },
  {
    country: "Nigeria",
    messagebird_cost_gbp: "0.208",
    gbp_price: "0.415",
    usd_price: "0.543",
    is_range: false,
    priority: -1,
  },
  {
    country: "Niue",
    messagebird_cost_gbp: "0.094",
    gbp_price: "0.188",
    usd_price: "0.246",
    is_range: false,
    priority: -1,
  },
  {
    country: "North Korea",
    messagebird_cost_gbp: "0.069",
    gbp_price: "0.137",
    usd_price: "0.179",
    is_range: false,
    priority: -1,
  },
  {
    country: "North Macedonia",
    messagebird_cost_gbp: "0.053",
    gbp_price: "0.106",
    usd_price: "0.139",
    is_range: false,
    priority: -1,
  },
  {
    country: "Norway",
    messagebird_cost_gbp: "0.049",
    gbp_price: "0.098",
    usd_price: "0.128",
    is_range: false,
    priority: -1,
  },
  {
    country: "Oman",
    messagebird_cost_gbp: "0.102",
    gbp_price: "0.205",
    usd_price: "0.268",
    is_range: false,
    priority: -1,
  },
  {
    country: "Pakistan",
    messagebird_cost_gbp: "0.251",
    gbp_price: "0.501",
    usd_price: "0.655",
    is_range: false,
    priority: -1,
  },
  {
    country: "Palau",
    messagebird_cost_gbp: "0.071",
    gbp_price: "0.143",
    usd_price: "0.187",
    is_range: false,
    priority: -1,
  },
  {
    country: "Panama",
    messagebird_cost_gbp: "0.124",
    gbp_price: "0.248",
    usd_price: "0.324",
    is_range: false,
    priority: -1,
  },
  {
    country: "Papua New Guinea",
    messagebird_cost_gbp: "0.128",
    gbp_price: "0.257",
    usd_price: "0.336",
    is_range: false,
    priority: -1,
  },
  {
    country: "Paraguay",
    messagebird_cost_gbp: "0.065",
    gbp_price: "0.131",
    usd_price: "0.171",
    is_range: false,
    priority: -1,
  },
  {
    country: "Peru",
    messagebird_cost_gbp: "0.093",
    gbp_price: "0.185",
    usd_price: "0.242",
    is_range: false,
    priority: -1,
  },
  {
    country: "Philippines",
    messagebird_cost_gbp: "0.139",
    gbp_price: "0.279",
    usd_price: "0.364",
    is_range: false,
    priority: -1,
  },
  {
    country: "Poland",
    messagebird_cost_gbp: "0.031",
    gbp_price: "0.062",
    usd_price: "0.081",
    is_range: false,
    priority: -1,
  },
  {
    country: "Portugal",
    messagebird_cost_gbp: "0.034",
    gbp_price: "0.068",
    usd_price: "0.088",
    is_range: false,
    priority: -1,
  },
  {
    country: "Puerto Rico",
    messagebird_cost_gbp: "0.031",
    gbp_price: "0.062",
    usd_price: "0.081",
    is_range: false,
    priority: -1,
  },
  {
    country: "Qatar",
    messagebird_cost_gbp: "0.155",
    gbp_price: "0.311",
    usd_price: "0.406",
    is_range: false,
    priority: -1,
  },
  {
    country: "Reunion",
    messagebird_cost_gbp: "0.137",
    gbp_price: "0.273",
    usd_price: "0.358",
    is_range: false,
    priority: -1,
  },
  {
    country: "Romania",
    messagebird_cost_gbp: "0.048",
    gbp_price: "0.096",
    usd_price: "0.126",
    is_range: false,
    priority: -1,
  },
  {
    country: "Russian Federation",
    messagebird_cost_gbp: "0.507",
    gbp_price: "1.015",
    usd_price: "1.328",
    is_range: false,
    priority: -1,
  },
  {
    country: "Rwanda",
    messagebird_cost_gbp: "0.137",
    gbp_price: "0.274",
    usd_price: "0.358",
    is_range: false,
    priority: -1,
  },
  {
    country: "Samoa",
    messagebird_cost_gbp: "0.131",
    gbp_price: "0.262",
    usd_price: "0.342",
    is_range: false,
    priority: -1,
  },
  {
    country: "San Marino",
    messagebird_cost_gbp: "0.079",
    gbp_price: "0.158",
    usd_price: "0.207",
    is_range: false,
    priority: -1,
  },
  {
    country: "Sao Tome and Principe",
    messagebird_cost_gbp: "0.093",
    gbp_price: "0.187",
    usd_price: "0.245",
    is_range: false,
    priority: -1,
  },
  {
    country: "Saudi Arabia",
    messagebird_cost_gbp: "0.099",
    gbp_price: "0.197",
    usd_price: "0.258",
    is_range: false,
    priority: -1,
  },
  {
    country: "Senegal",
    messagebird_cost_gbp: "0.182",
    gbp_price: "0.365",
    usd_price: "0.477",
    is_range: false,
    priority: -1,
  },
  {
    country: "Serbia",
    messagebird_cost_gbp: "0.173",
    gbp_price: "0.346",
    usd_price: "0.452",
    is_range: false,
    priority: -1,
  },
  {
    country: "Seychelles",
    messagebird_cost_gbp: "0.092",
    gbp_price: "0.184",
    usd_price: "0.241",
    is_range: false,
    priority: -1,
  },
  {
    country: "Sierra Leone",
    messagebird_cost_gbp: "0.136",
    gbp_price: "0.271",
    usd_price: "0.355",
    is_range: false,
    priority: -1,
  },
  {
    country: "Singapore",
    messagebird_cost_gbp: "0.031",
    gbp_price: "0.063",
    usd_price: "0.082",
    is_range: false,
    priority: -1,
  },
  {
    country: "Slovakia",
    messagebird_cost_gbp: "0.058",
    gbp_price: "0.117",
    usd_price: "0.153",
    is_range: false,
    priority: -1,
  },
  {
    country: "Slovenia",
    messagebird_cost_gbp: "0.113",
    gbp_price: "0.226",
    usd_price: "0.295",
    is_range: false,
    priority: -1,
  },
  {
    country: "Solomon Islands",
    messagebird_cost_gbp: "0.061",
    gbp_price: "0.122",
    usd_price: "0.160",
    is_range: false,
    priority: -1,
  },
  {
    country: "Somalia",
    messagebird_cost_gbp: "0.168",
    gbp_price: "0.336",
    usd_price: "0.440",
    is_range: false,
    priority: -1,
  },
  {
    country: "South Africa",
    messagebird_cost_gbp: "0.010",
    gbp_price: "0.020",
    usd_price: "0.026",
    is_range: false,
    priority: 4,
  },
  {
    country: "South Korea",
    messagebird_cost_gbp: "0.035",
    gbp_price: "0.071",
    usd_price: "0.092",
    is_range: false,
    priority: -1,
  },
  {
    country: "South Sudan",
    messagebird_cost_gbp: "0.168",
    gbp_price: "0.335",
    usd_price: "0.439",
    is_range: false,
    priority: -1,
  },
  {
    country: "Spain",
    messagebird_cost_gbp: "0.063",
    gbp_price: "0.125",
    usd_price: "0.164",
    is_range: false,
    priority: -1,
  },
  {
    country: "Sri Lanka",
    messagebird_cost_gbp: "0.278",
    gbp_price: "0.557",
    usd_price: "0.728",
    is_range: false,
    priority: -1,
  },
  {
    country: "St. Helena",
    messagebird_cost_gbp: "0.080",
    gbp_price: "0.160",
    usd_price: "0.210",
    is_range: false,
    priority: -1,
  },
  {
    country: "St. Kitts and Nevis",
    messagebird_cost_gbp: "0.101",
    gbp_price: "0.201",
    usd_price: "0.263",
    is_range: false,
    priority: -1,
  },
  {
    country: "St. Lucia",
    messagebird_cost_gbp: "0.097",
    gbp_price: "0.195",
    usd_price: "0.255",
    is_range: false,
    priority: -1,
  },
  {
    country: "St. Pierre and Miquelon",
    messagebird_cost_gbp: "0.108",
    gbp_price: "0.216",
    usd_price: "0.282",
    is_range: false,
    priority: -1,
  },
  {
    country: "St. Vincent and the Grenadines",
    messagebird_cost_gbp: "0.137",
    gbp_price: "0.274",
    usd_price: "0.358",
    is_range: false,
    priority: -1,
  },
  {
    country: "Sudan",
    messagebird_cost_gbp: "0.214",
    gbp_price: "0.429",
    usd_price: "0.561",
    is_range: false,
    priority: -1,
  },
  {
    country: "Suriname",
    messagebird_cost_gbp: "0.100",
    gbp_price: "0.200",
    usd_price: "0.261",
    is_range: false,
    priority: -1,
  },
  {
    country: "Sweden",
    messagebird_cost_gbp: "0.043",
    gbp_price: "0.087",
    usd_price: "0.113",
    is_range: false,
    priority: -1,
  },
  {
    country: "Switzerland",
    messagebird_cost_gbp: "0.052",
    gbp_price: "0.104",
    usd_price: "0.136",
    is_range: false,
    priority: -1,
  },
  {
    country: "Taiwan",
    messagebird_cost_gbp: "0.041",
    gbp_price: "0.081",
    usd_price: "0.106",
    is_range: false,
    priority: -1,
  },
  {
    country: "Tajikistan",
    messagebird_cost_gbp: "0.341",
    gbp_price: "0.682",
    usd_price: "0.892",
    is_range: false,
    priority: -1,
  },
  {
    country: "Tanzania",
    messagebird_cost_gbp: "0.192",
    gbp_price: "0.385",
    usd_price: "0.503",
    is_range: false,
    priority: -1,
  },
  {
    country: "Thailand",
    messagebird_cost_gbp: "0.022",
    gbp_price: "0.044",
    usd_price: "0.057",
    is_range: false,
    priority: -1,
  },
  {
    country: "Timor-Leste",
    messagebird_cost_gbp: "0.083",
    gbp_price: "0.167",
    usd_price: "0.218",
    is_range: false,
    priority: -1,
  },
  {
    country: "Togo",
    messagebird_cost_gbp: "0.149",
    gbp_price: "0.297",
    usd_price: "0.389",
    is_range: false,
    priority: -1,
  },
  {
    country: "Tonga",
    messagebird_cost_gbp: "0.090",
    gbp_price: "0.181",
    usd_price: "0.237",
    is_range: false,
    priority: -1,
  },
  {
    country: "Trinidad and Tobago",
    messagebird_cost_gbp: "0.172",
    gbp_price: "0.343",
    usd_price: "0.449",
    is_range: false,
    priority: -1,
  },
  {
    country: "Tunisia",
    messagebird_cost_gbp: "0.201",
    gbp_price: "0.401",
    usd_price: "0.525",
    is_range: false,
    priority: -1,
  },
  {
    country: "Turkey",
    messagebird_cost_gbp: "0.022",
    gbp_price: "0.044",
    usd_price: "0.057",
    is_range: false,
    priority: -1,
  },
  {
    country: "Turkmenistan",
    messagebird_cost_gbp: "0.227",
    gbp_price: "0.453",
    usd_price: "0.593",
    is_range: false,
    priority: -1,
  },
  {
    country: "Turks and Caicos Islands",
    messagebird_cost_gbp: "0.096",
    gbp_price: "0.192",
    usd_price: "0.251",
    is_range: false,
    priority: -1,
  },
  {
    country: "Tuvalu",
    messagebird_cost_gbp: "0.093",
    gbp_price: "0.187",
    usd_price: "0.244",
    is_range: false,
    priority: -1,
  },
  {
    country: "US Virgin Islands",
    messagebird_cost_gbp: "0.014",
    gbp_price: "0.027",
    usd_price: "0.036",
    is_range: false,
    priority: -1,
  },
  {
    country: "Uganda",
    messagebird_cost_gbp: "0.149",
    gbp_price: "0.299",
    usd_price: "0.391",
    is_range: false,
    priority: -1,
  },
  {
    country: "Ukraine",
    messagebird_cost_gbp: "0.125",
    gbp_price: "0.250",
    usd_price: "0.327",
    is_range: false,
    priority: -1,
  },
  {
    country: "United Arab Emirates",
    messagebird_cost_gbp: "0.081",
    gbp_price: "0.162",
    usd_price: "0.212",
    is_range: false,
    priority: -1,
  },
  {
    country: "United Kingdom",
    messagebird_cost_gbp: "0.020 - 0.034",
    gbp_price: "0.040 - 0.068",
    usd_price: "0.052 - 0.089",
    is_range: true,
    priority: 2,
  },
  {
    country: "United States of America",
    messagebird_cost_gbp: "0.003 - 0.005",
    gbp_price: "0.006 - 0.011",
    usd_price: "0.008 - 0.014",
    is_range: true,
    priority: 0,
  },
  {
    country: "Uruguay",
    messagebird_cost_gbp: "0.060",
    gbp_price: "0.121",
    usd_price: "0.158",
    is_range: false,
    priority: -1,
  },
  {
    country: "Uzbekistan",
    messagebird_cost_gbp: "0.271",
    gbp_price: "0.542",
    usd_price: "0.710",
    is_range: false,
    priority: -1,
  },
  {
    country: "Vanuatu",
    messagebird_cost_gbp: "0.124",
    gbp_price: "0.249",
    usd_price: "0.326",
    is_range: false,
    priority: -1,
  },
  {
    country: "Venezuela",
    messagebird_cost_gbp: "0.063",
    gbp_price: "0.127",
    usd_price: "0.166",
    is_range: false,
    priority: -1,
  },
  {
    country: "Viet Nam",
    messagebird_cost_gbp: "0.111",
    gbp_price: "0.222",
    usd_price: "0.290",
    is_range: false,
    priority: -1,
  },
  {
    country: "Wallis and Futuna Islands",
    messagebird_cost_gbp: "0.068",
    gbp_price: "0.135",
    usd_price: "0.177",
    is_range: false,
    priority: -1,
  },
  {
    country: "Yemen",
    messagebird_cost_gbp: "0.181",
    gbp_price: "0.362",
    usd_price: "0.474",
    is_range: false,
    priority: -1,
  },
  {
    country: "Zambia",
    messagebird_cost_gbp: "0.230",
    gbp_price: "0.461",
    usd_price: "0.603",
    is_range: false,
    priority: -1,
  },
  {
    country: "Zimbabwe",
    messagebird_cost_gbp: "0.148",
    gbp_price: "0.297",
    usd_price: "0.388",
    is_range: false,
    priority: -1,
  },
];
