export const reps = [
  {
    rep_name: "Sam",
    callbooker_url: "/book-a-call/sam/",
    img_path: "/img/reps/sam_blue.webp",
    hermes_admin_id: 1,
    alt_rep_name: "Fionn",
    alt_rep_hermes_admin_id: 2,
    description:
      "Sam is TutorCruncher's frontline sales expert. He helps companies of all sizes get the most out of TutorCruncher and transform their businesses, making them more efficient, more cost effective, and more flexible. Book a call with him today to talk through what options you have when using TutorCruncher and how it could help to make your life easier.",
  },
  {
    rep_name: "Fionn",
    callbooker_url: "/book-a-call/fionn/",
    img_path: "/img/reps/fionn_blue.webp",
    hermes_admin_id: 2,
    alt_rep_name: "Sam",
    alt_callbooker_url: "/book-a-call/sam/",
    alt_rep_hermes_admin_id: 1,
    description:
      "Fionn works with established businesses whose annual revenue is greater than £1.2m a year. He has experience with; global franchises, custom development and bespoke API automations. Fionn is a specialist in helping people adapt their current workflows and transition from legacy systems to TutorCruncher.",
  },
  {
    rep_name: "Tony",
    callbooker_url: "/book-a-call/tony/",
    img_path: "/img/reps/tony_blue.webp",
    hermes_admin_id: 8,
    alt_rep_name: "Sam",
    alt_callbooker_url: "/book-a-call/sam/",
    alt_rep_hermes_admin_id: 1,
    description:
      "Tony is a recent graduate of Northern Illinois University residing in the city of Chicago, bringing with him a wealth of experience in sales and account management within the telecommunications industry. Now, poised to leverage his expertise as a Sales Consultant for TutorCruncher, he aims to revolutionize businesses of all scales by optimizing their operational workflows through TutorCruncher's innovative platform.",
  },
  {
    rep_name: "Raashi",
    callbooker_url: "/book-a-call/raashi/",
    img_path: "/img/reps/raashi_blue.webp",
    hermes_admin_id: 4,
    alt_rep_name: "Maahi",
    alt_callbooker_url: "/book-a-call/maahi/",
    alt_rep_hermes_admin_id: 3,
    description: "",
    is_support: true,
  },
  {
    rep_name: "Maahi",
    callbooker_url: "/book-a-call/maahi/",
    img_path: "/img/reps/maahi_blue.webp",
    hermes_admin_id: 3,
    alt_rep_name: "Raashi",
    alt_callbooker_url: "/book-a-call/raashi/",
    alt_rep_hermes_admin_id: 4,
    description: "",
    is_support: true,
  },
];
