// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Category field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Featured Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Publish Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date the article was published
   * - **API ID Path**: article.publishDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishDate: prismic.DateField;

  /**
   * Content field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Author image  field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author name field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Custom URL field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.custom_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  custom_url: prismic.KeyTextField;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Featured Within Footer field in *Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.featured_within_footer
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  featured_within_footer: prismic.BooleanField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Contact → Locations*
 */
export interface ContactDocumentDataLocationsItem {
  /**
   * Name field in *Contact → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Address field in *Contact → Locations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Email field in *Contact → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone number field in *Contact → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Opening hours field in *Contact → Locations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].opening_hours
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  opening_hours: prismic.RichTextField;

  /**
   * Longitude field in *Contact → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].longitude
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  longitude: prismic.KeyTextField;

  /**
   * Latitude field in *Contact → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[].latitude
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  latitude: prismic.KeyTextField;
}

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Content field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Locations field in *Contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.locations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  locations: prismic.GroupField<Simplify<ContactDocumentDataLocationsItem>>;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type FeatureDocumentDataSlicesSlice = never;

/**
 * Content for Feature documents
 */
interface FeatureDocumentData {
  /**
   * Heading field in *Feature*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Slice Zone field in *Feature*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeatureDocumentDataSlicesSlice> /**
   * List image field in *Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.list_image
   * - **Tab**: List
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  list_image: prismic.ImageField<never>;

  /**
   * List Text field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.list_text
   * - **Tab**: List
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_text: prismic.RichTextField /**
   * Meta Title field in *Feature*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: feature.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Feature*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: feature.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Feature document from Prismic
 *
 * - **API ID**: `feature`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeatureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeatureDocumentData>,
    "feature",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | AccordionsSlice
  | TestimonialsSlice
  | LogosSlice
  | TextImageGridSlice
  | ArticlesSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Heading field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type IntegrationDocumentDataSlicesSlice = never;

/**
 * Content for Integration documents
 */
interface IntegrationDocumentData {
  /**
   * Title field in *Integration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Logo field in *Integration*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Category field in *Integration*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    "Payments" | "Online Classrooms" | "Integrations" | "Single Sign Ons"
  >;

  /**
   * Screenshot field in *Integration*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.screenshot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Description field in *Integration*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Intro field in *Integration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Slice Zone field in *Integration*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IntegrationDocumentDataSlicesSlice> /**
   * Meta Title field in *Integration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: integration.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Integration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: integration.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Integration*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Integration document from Prismic
 *
 * - **API ID**: `integration`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntegrationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IntegrationDocumentData>,
    "integration",
    Lang
  >;

type IntegrationsDocumentDataSlicesSlice = never;

/**
 * Content for Integrations documents
 */
interface IntegrationsDocumentData {
  /**
   * Heading field in *Integrations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Slice Zone field in *Integrations*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IntegrationsDocumentDataSlicesSlice> /**
   * Meta Title field in *Integrations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: integrations.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Integrations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: integrations.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Integrations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Integrations document from Prismic
 *
 * - **API ID**: `integrations`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntegrationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IntegrationsDocumentData>,
    "integrations",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Homepage Label field in *Navigation*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Label for the homepage link
   * - **API ID Path**: navigation.homepageLabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  homepageLabel: prismic.TitleField;

  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StandOutFeaturesSlice
  | YoutubeSlice
  | StatsSlice
  | TestimonialsSlice
  | CallToActionSlice
  | TeamListSlice
  | TextImageGridSlice
  | FaqsSlice
  | BodyTextSlice
  | ArticlesSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PricingDocumentDataSlicesSlice = BodyTextSlice;

/**
 * Content for Pricing documents
 */
interface PricingDocumentData {
  /**
   * Heading field in *Pricing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Slice Zone field in *Pricing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PricingDocumentDataSlicesSlice> /**
   * Meta Title field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pricing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pricing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Pricing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Pricing document from Prismic
 *
 * - **API ID**: `pricing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PricingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PricingDocumentData>,
    "pricing",
    Lang
  >;

/**
 * Content for Release documents
 */
interface ReleaseDocumentData {
  /**
   * Release Name field in *Release*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.release_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  release_name: prismic.KeyTextField;

  /**
   * Date field in *Release*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: release.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Changes field in *Release*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.changes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  changes: prismic.RichTextField;
}

/**
 * Release document from Prismic
 *
 * - **API ID**: `release`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleaseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReleaseDocumentData>,
    "release",
    Lang
  >;

type ReleasesDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Releases documents
 */
interface ReleasesDocumentData {
  /**
   * Slice Zone field in *Releases*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReleasesDocumentDataSlicesSlice> /**
   * Meta Title field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: releases.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: releases.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Releases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Releases document from Prismic
 *
 * - **API ID**: `releases`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleasesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReleasesDocumentData>,
    "releases",
    Lang
  >;

type ReviewsDocumentDataSlicesSlice = never;

/**
 * Content for Reviews documents
 */
interface ReviewsDocumentData {
  /**
   * Heading field in *Reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Slice Zone field in *Reviews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewsDocumentDataSlicesSlice> /**
   * Meta Title field in *Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: reviews.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: reviews.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Reviews document from Prismic
 *
 * - **API ID**: `reviews`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsDocumentData>,
    "reviews",
    Lang
  >;

type SolutionsDocumentDataSlicesSlice =
  | TextImageGridSlice
  | LogosSlice
  | AccordionsSlice
  | TestimonialsSlice
  | StatsSlice
  | YoutubeSlice
  | TeamListSlice
  | HeroSlice
  | CallToActionSlice
  | StandOutFeaturesSlice
  | BodyTextSlice
  | ArticlesSlice
  | FaqsSlice;

/**
 * Content for Solution documents
 */
interface SolutionsDocumentData {
  /**
   * Slice Zone field in *Solution*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SolutionsDocumentDataSlicesSlice> /**
   * Meta Title field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: solutions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: solutions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Solution*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Solution document from Prismic
 *
 * - **API ID**: `solutions`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SolutionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SolutionsDocumentData>,
    "solutions",
    Lang
  >;

type TestimonialDocumentDataSlicesSlice = never;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Short Testimonial field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.short_testimonial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_testimonial: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.testimonial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;

  /**
   * Company logo field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Reviewer image field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.reviewer_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  reviewer_image: prismic.ImageField<never>;

  /**
   * Reviewer name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.reviewer_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewer_name: prismic.KeyTextField;

  /**
   * Reviewer role field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.reviewer_role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewer_role: prismic.KeyTextField;

  /**
   * Slice Zone field in *Testimonial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestimonialDocumentDataSlicesSlice>;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | CategoryDocument
  | ContactDocument
  | FeatureDocument
  | HomePageDocument
  | IntegrationDocument
  | IntegrationsDocument
  | NavigationDocument
  | PageDocument
  | PricingDocument
  | ReleaseDocument
  | ReleasesDocument
  | ReviewsDocument
  | SolutionsDocument
  | TestimonialDocument;

/**
 * Item in *Accordions → Default → Primary → Content*
 */
export interface AccordionsSliceDefaultPrimaryContentItem {
  /**
   * Heading field in *Accordions → Default → Primary → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordions.default.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Accordions → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordions.default.primary.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Accordions → Default → Primary → Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accordions.default.primary.content[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Accordions → Default → Primary*
 */
export interface AccordionsSliceDefaultPrimary {
  /**
   * Heading field in *Accordions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordions.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background colour field in *Accordions → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cream
   * - **API ID Path**: accordions.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_colour: prismic.SelectField<"Cream" | "Blue", "filled">;

  /**
   * Content field in *Accordions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordions.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<AccordionsSliceDefaultPrimaryContentItem>
  >;
}

/**
 * Default variation for Accordions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Accordions*
 */
type AccordionsSliceVariation = AccordionsSliceDefault;

/**
 * Accordions Shared Slice
 *
 * - **API ID**: `accordions`
 * - **Description**: Accordions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionsSlice = prismic.SharedSlice<
  "accordions",
  AccordionsSliceVariation
>;

/**
 * Item in *Articles → Default → Primary → Articles*
 */
export interface ArticlesSliceDefaultPrimaryArticlesItem {
  /**
   * Article field in *Articles → Default → Primary → Articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.articles[].article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.ContentRelationshipField<"article">;
}

/**
 * Primary content in *Articles → Default → Primary*
 */
export interface ArticlesSliceDefaultPrimary {
  /**
   * Heading field in *Articles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Show all button field in *Articles → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: articles.default.primary.show_all_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_all_button: prismic.BooleanField;

  /**
   * Articles field in *Articles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.articles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<ArticlesSliceDefaultPrimaryArticlesItem>
  >;
}

/**
 * Default variation for Articles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Articles → Articles - By Category → Primary*
 */
export interface ArticlesSliceArticlesByCategoryPrimary {
  /**
   * Heading field in *Articles → Articles - By Category → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.articlesByCategory.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Show all button field in *Articles → Articles - By Category → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: articles.articlesByCategory.primary.show_all_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_all_button: prismic.BooleanField;

  /**
   * Category field in *Articles → Articles - By Category → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.articlesByCategory.primary.category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

/**
 * Articles - By Category variation for Articles Slice
 *
 * - **API ID**: `articlesByCategory`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSliceArticlesByCategory = prismic.SharedSliceVariation<
  "articlesByCategory",
  Simplify<ArticlesSliceArticlesByCategoryPrimary>,
  never
>;

/**
 * Slice variation for *Articles*
 */
type ArticlesSliceVariation =
  | ArticlesSliceDefault
  | ArticlesSliceArticlesByCategory;

/**
 * Articles Shared Slice
 *
 * - **API ID**: `articles`
 * - **Description**: Articles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSlice = prismic.SharedSlice<
  "articles",
  ArticlesSliceVariation
>;

/**
 * Primary content in *Body → Default → Primary*
 */
export interface BodyTextSliceDefaultPrimary {
  /**
   * Content field in *Body → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Background colour field in *Body → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: body_text.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_colour: prismic.SelectField<"White" | "Blue" | "Cream">;
}

/**
 * Default variation for Body Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BodyTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BodyTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Body*
 */
type BodyTextSliceVariation = BodyTextSliceDefault;

/**
 * Body Shared Slice
 *
 * - **API ID**: `body_text`
 * - **Description**: BodyText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BodyTextSlice = prismic.SharedSlice<
  "body_text",
  BodyTextSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Background colour field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cream
   * - **API ID Path**: call_to_action.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_colour: prismic.SelectField<"Cream" | "Blue", "filled">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → Faqs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *Faqs → Default → Primary → Faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faqs → Default → Primary → Faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Faqs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Solution Hero → Primary*
 */
export interface HeroSliceSolutionHeroPrimary {
  /**
   * Heading field in *Hero → Solution Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.solutionHero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *Hero → Solution Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.solutionHero.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Pricing Tier field in *Hero → Solution Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.solutionHero.primary.pricing_tier
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  pricing_tier: prismic.SelectField<"payg" | "startup" | "enterprise">;
}

/**
 * Solution Hero variation for Hero Slice
 *
 * - **API ID**: `solutionHero`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSolutionHero = prismic.SharedSliceVariation<
  "solutionHero",
  Simplify<HeroSliceSolutionHeroPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceSolutionHero;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Logos → Default → Primary → Logo*
 */
export interface LogosSliceDefaultPrimaryLogoItem {
  /**
   * Image field in *Logos → Default → Primary → Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logo[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
  /**
   * Heading field in *Logos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Logo field in *Logos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logo: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryLogoItem>>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<"logos", LogosSliceVariation>;

/**
 * Item in *StandOutFeatures → Default → Primary → Features*
 */
export interface StandOutFeaturesSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *StandOutFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *StandOutFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Intro field in *StandOutFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.features[].intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Content field in *StandOutFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.features[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *StandOutFeatures → Default → Primary*
 */
export interface StandOutFeaturesSliceDefaultPrimary {
  /**
   * Title field in *StandOutFeatures → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Features field in *StandOutFeatures → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stand_out_features.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<StandOutFeaturesSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for StandOutFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandOutFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StandOutFeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StandOutFeatures*
 */
type StandOutFeaturesSliceVariation = StandOutFeaturesSliceDefault;

/**
 * StandOutFeatures Shared Slice
 *
 * - **API ID**: `stand_out_features`
 * - **Description**: StandOutFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandOutFeaturesSlice = prismic.SharedSlice<
  "stand_out_features",
  StandOutFeaturesSliceVariation
>;

/**
 * Item in *Stats → Default → Primary → Stats*
 */
export interface StatsSliceDefaultPrimaryStatsItem {
  /**
   * Image field in *Stats → Default → Primary → Stats*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Percent field in *Stats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[].percent
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  percent: prismic.KeyTextField;

  /**
   * Description field in *Stats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface StatsSliceDefaultPrimary {
  /**
   * Heading field in *Stats → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Stats field in *Stats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<StatsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSlice = prismic.SharedSlice<"stats", StatsSliceVariation>;

/**
 * Item in *TeamList → Default → Primary → Team Members*
 */
export interface TeamListSliceDefaultPrimaryTeamMembersItem {
  /**
   * Name field in *TeamList → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *TeamList → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_members[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Intro field in *TeamList → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_members[].intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Image field in *TeamList → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_members[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *TeamList → Sales Team → Primary → Team Members*
 */
export interface TeamListSliceSalesTeamPrimaryTeamMembersItem {
  /**
   * Name field in *TeamList → Sales Team → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.team_members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *TeamList → Sales Team → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.team_members[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Intro field in *TeamList → Sales Team → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.team_members[].intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Image field in *TeamList → Sales Team → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.team_members[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TeamList → Default → Primary*
 */
export interface TeamListSliceDefaultPrimary {
  /**
   * Heading field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Team Members field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_members: prismic.GroupField<
    Simplify<TeamListSliceDefaultPrimaryTeamMembersItem>
  >;
}

/**
 * Default variation for TeamList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamListSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TeamList → Sales Team → Primary*
 */
export interface TeamListSliceSalesTeamPrimary {
  /**
   * Heading field in *TeamList → Sales Team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Team Members field in *TeamList → Sales Team → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.salesTeam.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_members: prismic.GroupField<
    Simplify<TeamListSliceSalesTeamPrimaryTeamMembersItem>
  >;
}

/**
 * Sales Team variation for TeamList Slice
 *
 * - **API ID**: `salesTeam`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSliceSalesTeam = prismic.SharedSliceVariation<
  "salesTeam",
  Simplify<TeamListSliceSalesTeamPrimary>,
  never
>;

/**
 * Slice variation for *TeamList*
 */
type TeamListSliceVariation = TeamListSliceDefault | TeamListSliceSalesTeam;

/**
 * TeamList Shared Slice
 *
 * - **API ID**: `team_list`
 * - **Description**: TeamList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSlice = prismic.SharedSlice<
  "team_list",
  TeamListSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Testimonial  field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *AlternatingGrid → default → Primary → content*
 */
export interface TextImageGridSliceDefaultPrimaryContentItem {
  /**
   * heading field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button text field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button link field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * image field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image postion field in *AlternatingGrid → default → Primary → content*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Right
   * - **API ID Path**: text_image_grid.default.primary.content[].image_postion
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_postion: prismic.SelectField<"Right" | "Left", "filled">;
}

/**
 * Item in *AlternatingGrid → has background → Primary → content*
 */
export interface TextImageGridSliceWithBackgroundPrimaryContentItem {
  /**
   * heading field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button text field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button link field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * image field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image postion field in *AlternatingGrid → has background → Primary → content*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Right
   * - **API ID Path**: text_image_grid.withBackground.primary.content[].image_postion
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_postion: prismic.SelectField<"Right" | "Left", "filled">;
}

/**
 * Primary content in *AlternatingGrid → default → Primary*
 */
export interface TextImageGridSliceDefaultPrimary {
  /**
   * Heading field in *AlternatingGrid → default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background colour field in *AlternatingGrid → default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cream
   * - **API ID Path**: text_image_grid.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_colour: prismic.SelectField<"Cream" | "Blue", "filled">;

  /**
   * content field in *AlternatingGrid → default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<TextImageGridSliceDefaultPrimaryContentItem>
  >;
}

/**
 * default variation for AlternatingGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternatingGrid → has background → Primary*
 */
export interface TextImageGridSliceWithBackgroundPrimary {
  /**
   * Heading field in *AlternatingGrid → has background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background colour field in *AlternatingGrid → has background → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cream
   * - **API ID Path**: text_image_grid.withBackground.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_colour: prismic.SelectField<"Cream" | "Blue", "filled">;

  /**
   * content field in *AlternatingGrid → has background → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_grid.withBackground.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<TextImageGridSliceWithBackgroundPrimaryContentItem>
  >;
}

/**
 * has background variation for AlternatingGrid Slice
 *
 * - **API ID**: `withBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageGridSliceWithBackground = prismic.SharedSliceVariation<
  "withBackground",
  Simplify<TextImageGridSliceWithBackgroundPrimary>,
  never
>;

/**
 * Slice variation for *AlternatingGrid*
 */
type TextImageGridSliceVariation =
  | TextImageGridSliceDefault
  | TextImageGridSliceWithBackground;

/**
 * AlternatingGrid Shared Slice
 *
 * - **API ID**: `text_image_grid`
 * - **Description**: TextImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageGridSlice = prismic.SharedSlice<
  "text_image_grid",
  TextImageGridSliceVariation
>;

/**
 * Primary content in *Youtube → Default → Primary*
 */
export interface YoutubeSliceDefaultPrimary {
  /**
   * Youtube ID field in *Youtube → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ID of the youtube video
   * - **API ID Path**: youtube.default.primary.youtube_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_id: prismic.KeyTextField;
}

/**
 * Default variation for Youtube Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YoutubeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Youtube*
 */
type YoutubeSliceVariation = YoutubeSliceDefault;

/**
 * Youtube Shared Slice
 *
 * - **API ID**: `youtube`
 * - **Description**: Youtube
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeSlice = prismic.SharedSlice<
  "youtube",
  YoutubeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataLocationsItem,
      ContactDocumentDataSlicesSlice,
      FeatureDocument,
      FeatureDocumentData,
      FeatureDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      IntegrationDocument,
      IntegrationDocumentData,
      IntegrationDocumentDataSlicesSlice,
      IntegrationsDocument,
      IntegrationsDocumentData,
      IntegrationsDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PricingDocument,
      PricingDocumentData,
      PricingDocumentDataSlicesSlice,
      ReleaseDocument,
      ReleaseDocumentData,
      ReleasesDocument,
      ReleasesDocumentData,
      ReleasesDocumentDataSlicesSlice,
      ReviewsDocument,
      ReviewsDocumentData,
      ReviewsDocumentDataSlicesSlice,
      SolutionsDocument,
      SolutionsDocumentData,
      SolutionsDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      TestimonialDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionsSlice,
      AccordionsSliceDefaultPrimaryContentItem,
      AccordionsSliceDefaultPrimary,
      AccordionsSliceVariation,
      AccordionsSliceDefault,
      ArticlesSlice,
      ArticlesSliceDefaultPrimaryArticlesItem,
      ArticlesSliceDefaultPrimary,
      ArticlesSliceArticlesByCategoryPrimary,
      ArticlesSliceVariation,
      ArticlesSliceDefault,
      ArticlesSliceArticlesByCategory,
      BodyTextSlice,
      BodyTextSliceDefaultPrimary,
      BodyTextSliceVariation,
      BodyTextSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSolutionHeroPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSolutionHero,
      LogosSlice,
      LogosSliceDefaultPrimaryLogoItem,
      LogosSliceDefaultPrimary,
      LogosSliceVariation,
      LogosSliceDefault,
      StandOutFeaturesSlice,
      StandOutFeaturesSliceDefaultPrimaryFeaturesItem,
      StandOutFeaturesSliceDefaultPrimary,
      StandOutFeaturesSliceVariation,
      StandOutFeaturesSliceDefault,
      StatsSlice,
      StatsSliceDefaultPrimaryStatsItem,
      StatsSliceDefaultPrimary,
      StatsSliceVariation,
      StatsSliceDefault,
      TeamListSlice,
      TeamListSliceDefaultPrimaryTeamMembersItem,
      TeamListSliceDefaultPrimary,
      TeamListSliceSalesTeamPrimaryTeamMembersItem,
      TeamListSliceSalesTeamPrimary,
      TeamListSliceVariation,
      TeamListSliceDefault,
      TeamListSliceSalesTeam,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextImageGridSlice,
      TextImageGridSliceDefaultPrimaryContentItem,
      TextImageGridSliceDefaultPrimary,
      TextImageGridSliceWithBackgroundPrimaryContentItem,
      TextImageGridSliceWithBackgroundPrimary,
      TextImageGridSliceVariation,
      TextImageGridSliceDefault,
      TextImageGridSliceWithBackground,
      YoutubeSlice,
      YoutubeSliceDefaultPrimary,
      YoutubeSliceVariation,
      YoutubeSliceDefault,
    };
  }
}
