const blogRedirects = [
  {
    source: '/how-to-start-a-tutoring-business',
    destination: '/blog/how-to-start-a-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/expand-tutoring-business',
    destination: '/blog/expand-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-business-growth',
    destination: '/blog/tutoring-business-growth',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-business-plan',
    destination: '/blog/tutoring-business-plan',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/tutoring-strategies',
    destination: '/blog/10-effective-tutoring-strategies-techniques-for-successful-learning',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/creating-a-positive-learning-environment',
    destination: '/blog/tutoring-online-creating-a-positive-learning-environment',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/online-tutoring-platforms',
    destination: '/blog/online-tutoring-platforms',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/new-online-whiteboard-options',
    destination: '/blog/new-online-whiteboard-options',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/how-to-structure-a-tutoring-session',
    destination: '/blog/how-to-structure-a-tutoring-session',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/start-up-costs-for-tutoring-business',
    destination: '/blog/start-up-costs-for-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business',
    destination: '/solutions/payg',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-contract-essentials',
    destination: '/blog/tutoring-contract-essentials',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/find-students-to-tutor',
    destination: '/blog/find-students-to-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/what-are-the-best-tutoring-jobs-understand-which-subjects-you-should-teach',
    destination: '/blog/what-are-the-best-tutoring-jobs-understand-which-subjects-you-should-teach',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/interview-tutors-for-tutoring-company',
    destination: '/blog/business-growth-interview-tutors-for-tutoring-company',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-be-a-better-tutor',
    destination: '/blog/how-to-be-a-better-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/how-to-continue-growing-your-tutoring-business-2020-tutoring-market-trends',
    destination: '/blog/how-to-continue-growing-your-tutoring-business-tutoring-market-trends',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/monitor-evaluate-tutors-performance',
    destination: '/blog/monitor-evaluate-tutors-performance',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/social-media-strategy-for-tutoring-businesses',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/how-to-advertise-your-tutoring-agency-online',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/legal-requirements-for-tutoring-business',
    destination: '/blog/legal-requirements-for-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/how-to-market-your-private-tuition-agency',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/5-social-media-tips-to-you-help-kick-start-your-online-presence',
    destination: '/blog',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/online-tutoring-trends',
    destination: '/blog/online-tutoring-trends',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/us/features/online-whiteboard',
    destination: '/integrations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/do-you-need-a-license-to-start-a-tutoring-business',
    destination: '/blog/do-you-need-a-license-to-start-a-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/taking-payment-easily/#accounting-made-easy',
    destination: '/features/billing-and-payroll',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/crm/#profiles',
    destination: '/features/tutor-client-student-management',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/crm/#mass-communication',
    destination: '/features/tutor-client-student-management',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/taking-payment-easily/#payment-gateway-integrations',
    destination: '/features/billing-and-payroll',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/intelligent-design',
    destination: '/features/security',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/integrate-your-website/#website-building',
    destination: '/features/customization',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/integrate-your-website/#',
    destination: '/features/customization',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/integrate-your-website',
    destination: '/features/customization',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/maintaining-tutor-scheduling',
    destination: '/blog/maintaining-tutor-scheduling',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/tutor-matching',
    destination: '/blog/starting-tutor-business-tutor-matching',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-get-tutoring-clients',
    destination: '/blog/how-to-get-tutoring-clients',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/hire-tutors-for-tutoring-company',
    destination: '/blog/hire-tutors-for-tutoring-company',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/where-to-advertise-tutoring-services',
    destination: '/blog/where-to-advertise-tutoring-services',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/remote-teaching-tips',
    destination: '/blog/remote-teaching-tips',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/why-continuing-your-childs-education-is-more-important-now-than-ever',
    destination: '/blog/why-continuing-your-child-s-education-is-more-important-now-than-ever',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/automated-emails',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/help/whiteboard-integration/online-whiteboard-integration',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/a-beginners-guide-to-tutoring-online',
    destination: '/blog/how-to-tutor-online-a-best-practice-guide',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/help/#tutorcruncher-video',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/tutor-marketing',
    destination: 'solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/the-effects-of-covid-19-on-the-tutoring-market-infographic',
    destination: '/blog/the-effects-of-covid-19-on-the-tutoring-market-infographic',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/exam-tutoring',
    destination: '/features/tutor-client-student-management',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/government-funding-for-tutoring',
    destination: '/blog/government-funding-for-tutoring',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/1bn-tuition-fund-provided-for-english-schools',
    destination: '/features/payment-integrations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/high-dosage-tutoring',
    destination: '/blog/tutoring-online-high-dosage-tutoring',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/average-tutoring-rates-uk',
    destination: '/blog/average-tutoring-rates-uk',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/average-tutoring-rates',
    destination: '/blog/average-tutoring-rates',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/best-online-whiteboards',
    destination: '/blog/best-online-whiteboards',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/5-tips-for-starting-a-tutoring-agency-in-2020',
    destination: '/blog/how-to-start-a-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/help/ad-hoc-charges/using-ad-hoc-charges',
    destination: '/features/payment-integrations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/help/jobs/charitable-donations/#2-how-do-i-add-a-charitable-donation-to-a-job',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/the-new-tutorcruncher-dashboard',
    destination: '/blog/the-new-tutorcruncher-dashboard',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/tutor-student-matching-ways',
    destination: '/solutions/payg',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-software-explained',
    destination: '/blog/tutoring-software-explained',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/first-tutoring-session-ideas',
    destination: '/blog/first-tutoring-session-ideas',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid',
    destination: '/features/payment-integrations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/are-tutoring-services-tax-deductible',
    destination: '/blog/are-tutoring-services-tax-deductible',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/new-tutorcruncher-feature-charitable-donations',
    destination: '/blog/new-tutorcruncher-feature-charitable-donations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/new-improved-client-booking',
    destination: '/blog/new-improved-client-booking',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/whiteboard',
    destination: '/integrations',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/scheduling',
    destination: '/features/calendar-and-scheduling',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/stimulating-learning-environment',
    destination: '/blog/tutoring-online-creating-a-positive-learning-environment',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/promote-tuition-agency-online-using-google-adwords',
    destination: '/solutions/startup',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-make-tutoring-fun',
    destination: '/blog/how-to-make-tutoring-fun',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/online-teaching-skills',
    destination: '/blog/7-online-teaching-skills-worth-developing',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/tutor-the-nation-university-students-and-private-tutors-help-underprivileged-kids-beat-covid-learning-loss',
    destination: '/blog/tutor-the-nation-university-students-and-private-tutors-help-underprivileged-kids-beat-covid-learning-loss',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/test-prep-business-management-software',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/tutoring-signs',
    destination: '/blog/tutoring-online-tutoring-signs',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/tutoring-side-hustle',
    destination: '/blog/tutoring-side-hustle',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/invoice-template-for-tutoring-services',
    destination: '/blog/invoice-template-for-tutoring-services',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/introducing-the-new-dashboard-for-tutors',
    destination: '/blog/introducing-the-new-dashboard-for-tutors',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/best-tutoring-software',
    destination: '/blog/best-tutoring-software',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-business-ideas',
    destination: '/blog/tutoring-business-ideas',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/benefits-of-tutor-management-software',
    destination: '/blog/benefits-of-tutor-management-software',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/how-to-become-a-certified-tutor',
    destination: '/blog/how-to-become-a-certified-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-bio-example',
    destination: '/blog/tutor-bio-example',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-online-vs-in-person',
    destination: '/blog/tutor-online-vs-in-person',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/education-technology-benefits-tutoring-companies',
    destination: '/blog/education-technology-benefits-tutoring-companies',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/lesson-tutoring-trends-uk',
    destination: '/blog/lesson-tutoring-trends-uk',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/crm',
    destination: '/features/tutor-client-student-management',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/taking-payment-easily',
    destination: '/features/billing-and-payroll',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/business-analytics',
    destination: '/features/total-business-oversight',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/calendar',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/what-are-the-benefits-of-online-tutoring',
    destination: '/blog/what-are-the-benefits-of-online-tutoring',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/grants-for-tutoring-business',
    destination: '/blog/grants-for-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/online-tutoring-tips',
    destination: '/blog/online-tutoring-tips',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/getting-paid/how-to-market-yourself-better-as-a-tutor',
    destination: '/blog/how-to-market-yourself-as-a-tutor-10-helpful-tips',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/tips-for-tutors-online-tutoring-best-practice',
    destination: '/blog/online-tutoring-tips',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/how-to-start-a-tutoring-agency',
    destination: '/blog/how-to-start-a-nanny-agency',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/find-a-tutor',
    destination: '/blog/where-to-advertise-tutoring-services',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/legal-implications-when-starting-a-tutoring-business',
    destination: '/blog/legal-requirements-for-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/mock-gcse-and-a-level-exams-2021-what-should-you-expect',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/what-is-the-true-cost-of-tutoring-in-the-uk',
    destination: '/blog/average-tutoring-rates-uk',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/marketing-strategies-tutoring-agencies',
    destination: '/blog/how-to-market-yourself-as-a-tutor-10-helpful-tips',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/private-tuition-market-in-the-uk-overview',
    destination: '/blog/average-tutoring-rates-uk',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/5-tips-for-starting-a-tutoring-agency-in-2020',
    destination: '/blog/how-to-start-a-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutor-management-software/top-ten-most-popular-online-whiteboards-2019',
    destination: '/blog/best-online-whiteboards',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/companies',
    destination: '/blog/where-to-advertise-tutoring-services',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/what-makes-a-great-tutor',
    destination: '/blog/how-to-be-a-better-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/tutoring-company-marketing',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/starting-tutor-business/onboarding-processes',
    destination: '/',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/business-coaching-101',
    destination: '/blog/tutor-online-vs-in-person',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/tutoring-strategies',
    destination: '/blog/10-effective-tutoring-strategies-techniques-for-successful-learning',
    permanent: true,
    statusCode: 301,
  },
    {
    source: '/blog/how-to-market-yourself-better-as-a-tutor',
    destination: '/blog/how-to-market-yourself-as-a-tutor-10-helpful-tips',
    permanent: true,
      statusCode: 301,
  },
  {
    source: '/blog/creating-a-positive-learning-environment',
    destination: '/blog/tutoring-online-creating-a-positive-learning-environment',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/online-teaching-skills',
    destination: '/blog/7-online-teaching-skills-worth-developing',
    permanent: true,
      statusCode: 301,
  },
  {
    source: '/blog/tutoring-online-how-to-become-a-certified-tutor',
    destination: '/blog/how-to-become-a-certified-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/interview-tutors-for-tutoring-company',
    destination: '/blog/business-growth-interview-tutors-for-tutoring-company',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/how-to-continue-growing-your-tutoring-business-2020-tutoring-market-trends',
    destination: '/blog/how-to-continue-growing-your-tutoring-business-tutoring-market-trends',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/5-social-media-tips-to-you-help-kick-start-your-online-presence',
    destination: '/blog',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/tutor-matching',
    destination: '/blog/starting-tutor-business-tutor-matching',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/why-continuing-your-childs-education-is-more-important-now-than-ever',
    destination: '/blog/why-continuing-your-child-s-education-is-more-important-now-than-ever',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/a-beginners-guide-to-tutoring-online',
    destination: '/blog/how-to-tutor-online-a-best-practice-guide',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/high-dosage-tutoring',
    destination: '/blog/tutoring-online-high-dosage-tutoring',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/tutoring-signs',
    destination: '/blog/tutoring-online-tutoring-signs',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/crm/revolutionising-tutoring-insights-from-syed-talha-founder-of-canonical-tutors',
    destination: '/blog/revolutionising-tutoring-insights-from-syed-talha-founder-of-canonical-tutors',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-make-a-tutoring-website',
    destination: '/blog/how-to-make-a-tutoring-website',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/social-media-for-online-tutors',
    destination: '/blog/social-media-for-online-tutors',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-online/a-brief-history-of-tutoring-infographic',
    destination: '/blog/a-brief-history-of-tutoring-infographic',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/uk-tutoring-financial-trends',
    destination: '/blog/online-tutoring-trends',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/uk-tutoring-financial-trends',
    destination: '/blog/online-tutoring-trends',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/features/tutorcruncher-socket',
    destination: '/blog/introducing-tutorcruncher-socket',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-blogs',
    destination: '/blog',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutoring-contract-essentials/',
    destination: '/blog/tutoring-contract-essentials',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/business-growth/pros-and-cons-of-online-studying',
    destination: '/blog/tutor-online-vs-in-person',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-get-tutoring-clients',
    destination: '/blog/how-to-get-tutoring-clients',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-start-a-tutoring-business-in-canada',
    destination: '/blog/how-to-start-a-tutoring-business-in-canada',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutorcruncher-vs-teachworks',
    destination: '/blog/tutorcruncher-vs-teachworks',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/tutorcruncher-vs-tutorbird',
    destination: '/blog/tutorcruncher-vs-tutorbird',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/how-to-become-a-self-employed-tutor',
    destination: '/blog/how-to-become-a-self-employed-tutor',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/how-to-continue-growing-your-tutoring-business-tutoring-market-trends',
    destination: '/blog/expand-tutoring-business',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/blog/tutoring-online-where-to-advertise-tutoring-services',
    destination: '/blog/where-to-advertise-tutoring-services',
    permanent: true,
    statusCode: 301,
  },
  {
    source: '/future-of-tutoring',
    destination: '/blog/future-of-tutoring',
    permanent: true,
    statusCode: 301,
  }
];

module.exports = blogRedirects;
