const miscellaneousRedirects = [
  {
    source: "/us",
    destination: "/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/us/features/tutorcruncher-socket",
    destination: "/features/customization",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/book-a-call/sam",
    destination: "/book-a-call/1",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/book-a-call/daniel",
    destination: "/book-a-call/1",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/book-a-call/fionn",
    destination: "/book-a-call/2",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/help",
    destination: "https://help.tutorcruncher.com/en/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/split-payments",
    destination: "/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/api",
    destination: "https://api.tutorcruncher.com/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/tutoring-online",
    destination: "/online-tutoring",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/change-log",
    destination: "/changes",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/gb/pricing",
    destination: "/pricing/gb",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/au/pricing",
    destination: "/pricing/au",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/eu/pricing",
    destination: "/pricing/eu",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/ca/pricing",
    destination: "/pricing/ca",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/us/pricing",
    destination: "/pricing/us",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/za/pricing",
    destination: "/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/undefined",
    destination: "/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/tutoring-online/star-rating-remains-the-most-important-part-of-a-review",
    destination: "/",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/split-payments-details",
    destination: "https://help.tutorcruncher.com/en/articles/8250106-split-payments-guide",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/tc-socket",
    destination: "https://help.tutorcruncher.com/en/articles/8255881-getting-started-with-tutorcruncher-socket",
    permanent: true,
    statusCode: 301,
  },
  {
    source: "/tutoring-online/zapier",
    destination: "https://help.tutorcruncher.com/en/articles/8250193-integrating-tutorcruncher-with-other-apps-via-zapier",
    permanent: true,
    statusCode: 301,
  },
];

module.exports = miscellaneousRedirects;
