export const STARTER_FEATURES = {
  Dashboard: [
    { title: "Lesson hours tracking", description: "" },
    { title: "Jobs tracking", description: "" },
    { title: "Activity feed", description: "" },
    { title: "Tracking invoices", description: "" },
  ],
  People: [
    { title: "User lists (tutors, students, clients)", description: "" },
    { title: "Client pipeline (CRM/sales)", description: "" },
    { title: "User profiles", description: "" },
    { title: "Direct debit and instant bank transfer", description: "" },
    { title: "Custom fields (per user)", description: "" },
    { title: "Secure payment method storage", description: "" },
    { title: "User import", description: "" },
  ],
  Activity: [
    { title: "Document storage/uploading", description: "" },
    { title: "Book tutors (tutor availability)", description: "" },
    { title: "Packages (automatic sales tool)", description: "" },
    { title: "Jobs", description: "" },
    { title: "Calendar", description: "" },
    { title: "Tutor availability", description: "" },
    { title: "Lesson reports", description: "" },
    { title: "Payment information (split or not)", description: "" },
    { title: "Ad-hoc charges (by tutors)", description: "" },
  ],
  Communications: [
    { title: "WhatsApp integration", description: "" },
    { title: "SMS", description: "" },
    { title: "Email & SMS tracking", description: "" },
    { title: "Lesson reminders", description: "" },
    { title: "Custom emails (domain)", description: "" },
    { title: "Email definitions (content)", description: "" },
    { title: "In-app chat", description: "" },
  ],
  Accounting: [
    { title: "EA workflow", description: "" },
    { title: "Split payments", description: "" },
    { title: "Lesson reports (by tutor)", description: "" },
    { title: "Credit requests (proforma invoice)", description: "" },
    { title: "Payments", description: "" },
    { title: "Payment orders", description: "" },
    { title: "Autocharge", description: "" },
  ],
  Analytics: [
    { title: "Basic accounting (income over time)", description: "" },
  ],
  Settings: [
    { title: "Terms & conditions / GDPR", description: "" },
    { title: "Labels (users, jobs etc)", description: "" },
    { title: "Locations (add to jobs)", description: "" },
    { title: "Custom translations", description: "" },
    { title: "Xero exports (configured)", description: "" },
    { title: "Custom theme (colours, fonts)", description: "" },
    { title: "Exports (csv files)", description: "" },
    { title: "Full system translation", description: "" },
  ],
  API: [{ title: "Integrate TC into your website", description: "" }],
  Support: [
    { title: "Onboarding support", description: "" },
    { title: "System support (chat)", description: "" },
    { title: "Expert content", description: "" },
    { title: "AI chatbot", description: "" },
  ],
  Integrations: [{ title: "Online whiteboard", description: "" }],
};

export const PRO_FEATURES = {
  Dashboard: [
    { title: "Macro tracking (analytics)", description: "" },
    { title: "Lesson hours tracking", description: "" },
    { title: "Jobs tracking", description: "" },
    { title: "Tutor tracking", description: "" },
    { title: "Activity feed", description: "" },
    { title: "Tracking invoices", description: "" },
    { title: "Configurable/customisable dashboard", description: "" },
  ],
  People: [
    { title: "Permissions (admin and ops)", description: "" },
    { title: "User lists (tutors, students, clients)", description: "" },
    { title: "Client pipeline (CRM/sales)", description: "" },
    { title: "User profiles", description: "" },
    { title: "User exports", description: "" },
    { title: "Direct debit and instant bank transfer", description: "" },
    { title: "Custom fields (per user)", description: "" },
    { title: "Client manager", description: "" },
    { title: "Attendance reports", description: "" },
    { title: "Tasks (reminder emails and dashboard)", description: "" },
    { title: "Secure payment method storage", description: "" },
    { title: "User import", description: "" },
    { title: "Tutor reviews (by clients)", description: "" },
    { title: "Tutor onboarding pipeline", description: "" },
  ],
  Activity: [
    { title: "Document storage/uploading", description: "" },
    { title: "Book tutors (tutor availability)", description: "" },
    { title: "Subscriptions (automatic billing)", description: "" },
    { title: "Tutor / student matching", description: "" },
    { title: "Custom fields for reports", description: "" },
    { title: "Packages (automatic sales tool)", description: "" },
    { title: "Jobs", description: "" },
    { title: "Calendar", description: "" },
    { title: "Tutor availability", description: "" },
    { title: "Task list (linked to users)", description: "" },
    { title: "Lesson reports", description: "" },
    { title: "Payment information (split or not)", description: "" },
    { title: "Ad-hoc charges (by tutors)", description: "" },
    { title: "LMS", description: "" },
  ],
  Communications: [
    { title: "Automated sales workflows", description: "" },
    { title: "WhatsApp integration", description: "" },
    { title: "SMS", description: "" },
    { title: "Broadcasts (drip feed?)", description: "" },
    { title: "Email & SMS tracking", description: "" },
    { title: "Email analytics (all)", description: "" },
    { title: "Lesson reminders", description: "" },
    { title: "Custom emails (domain)", description: "" },
    { title: "Custom email design (html templates)", description: "" },
    { title: "Email definitions (content)", description: "" },
    { title: "CC mail tracking", description: "" },
    { title: "In-app chat", description: "" },
    { title: "Automated sales workflows", description: "" },
  ],
  Accounting: [
    { title: "EA workflow", description: "" },
    { title: "Split payments", description: "" },
    { title: "Lesson reports (by tutor)", description: "" },
    { title: "Pay runs (bulk payments)", description: "" },
    { title: "Credit requests (proforma invoice)", description: "" },
    { title: "Payments", description: "" },
    { title: "Payment orders", description: "" },
    { title: "Autocharge", description: "" },
    { title: "Bulk automated payments", description: "" },
  ],
  Analytics: [
    { title: "Basic accounting (income over time)", description: "" },
    { title: "Activity (lesson hours)", description: "" },
    { title: "Advanced accounting", description: "" },
    { title: "Client conversion", description: "" },
    { title: "Graphs and aggregated analytics", description: "" },
  ],
  Settings: [
    { title: "Terms & conditions / GDPR", description: "" },
    { title: "Labels (users, jobs etc)", description: "" },
    { title: "Locations (add to jobs)", description: "" },
    { title: "Custom translations", description: "" },
    { title: "Xero exports (configured)", description: "" },
    { title: "Custom theme (colours, fonts)", description: "" },
    { title: "Exports (csv files)", description: "" },
    { title: "Full system translation", description: "" },
  ],
  API: [
    { title: "Integrate TC into your website", description: "" },
    { title: "Zapier API access", description: "" },
    { title: "Custom workflows in Zapier", description: "" },
    { title: "General enquiry form", description: "" },
  ],
  Support: [
    { title: "System support (video call)", description: "" },
    { title: "Onboarding support", description: "" },
    { title: "System support (chat)", description: "" },
    { title: "AI chatbot", description: "" },
    { title: "Expert content", description: "" },
    { title: "Advanced support", description: "" },
  ],
  Integrations: [{ title: "Online whiteboard", description: "" }],
};

export const ENTERPRISE_FEATURES = {
  Dashboard: [
    { title: "Macro tracking (analytics)", description: "" },
    { title: "Lesson hours tracking", description: "" },
    { title: "Jobs tracking", description: "" },
    { title: "Tutor tracking", description: "" },
    { title: "Activity feed", description: "" },
    { title: "Tracking invoices", description: "" },
    { title: "Configurable/customisable dashboard", description: "" },
  ],
  People: [
    { title: "Permissions (admin and ops)", description: "" },
    { title: "User lists (tutors, students, clients)", description: "" },
    { title: "Client pipeline (CRM/sales)", description: "" },
    { title: "User profiles", description: "" },
    { title: "User exports", description: "" },
    { title: "Direct debit and instant bank transfer", description: "" },
    { title: "Custom fields (per user)", description: "" },
    { title: "Attendance reports", description: "" },
    { title: "Client manager", description: "" },
    { title: "Tasks (reminder emails and dashboard)", description: "" },
    { title: "Secure payment method storage", description: "" },
    { title: "User import", description: "" },
    { title: "Tutor reviews (by clients)", description: "" },
    { title: "Tutor onboarding pipeline", description: "" },
  ],
  Activity: [
    { title: "Document storage/uploading", description: "" },
    { title: "Book tutors (tutor availability)", description: "" },
    { title: "Subscriptions (automatic billing)", description: "" },
    { title: "Tutor / student matching", description: "" },
    { title: "Custom fields for reports", description: "" },
    { title: "Packages (automatic sales tool)", description: "" },
    { title: "Jobs", description: "" },
    { title: "Calendar", description: "" },
    { title: "Tutor availability", description: "" },
    { title: "Task list (linked to users)", description: "" },
    { title: "Lesson reports", description: "" },
    { title: "Payment information (split or not)", description: "" },
    { title: "Ad-hoc charges (by tutors)", description: "" },
    { title: "LMS", description: "" },
  ],
  Communications: [
    { title: "Automated sales workflows", description: "" },
    { title: "WhatsApp integration", description: "" },
    { title: "SMS", description: "" },
    { title: "Broadcasts (drip feed?)", description: "" },
    { title: "Email & SMS tracking", description: "" },
    { title: "Email analytics (all)", description: "" },
    { title: "Lesson reminders", description: "" },
    { title: "Custom emails (domain)", description: "" },
    { title: "Custom email design (html templates)", description: "" },
    { title: "Email definitions (content)", description: "" },
    { title: "CC mail tracking", description: "" },
    { title: "In-app chat", description: "" },
    { title: "Automated sales workflows", description: "" },
  ],
  Accounting: [
    { title: "EA workflow", description: "" },
    { title: "Split payments", description: "" },
    { title: "Lesson reports (by tutor)", description: "" },
    { title: "Pay runs (bulk payments)", description: "" },
    { title: "Credit requests (proforma invoice)", description: "" },
    { title: "Payments", description: "" },
    { title: "Customisable invoices", description: "" },
    { title: "Payment orders", description: "" },
    { title: "Autocharge", description: "" },
    { title: "Bulk automated payments", description: "" },
  ],
  Analytics: [
    { title: "Basic accounting (income over time)", description: "" },
    { title: "Activity (lesson hours)", description: "" },
    { title: "Advanced accounting", description: "" },
    { title: "Client conversion", description: "" },
    { title: "Graphs and aggregated analytics", description: "" },
  ],
  Settings: [
    { title: "Terms & conditions / GDPR", description: "" },
    { title: "Google analytics integration", description: "" },
    { title: "Labels (users, jobs etc)", description: "" },
    { title: "Locations (add to jobs)", description: "" },
    { title: "Custom javascript", description: "" },
    { title: "Custom CSS", description: "" },
    { title: "Custom translations", description: "" },
    { title: "Editable document html templates", description: "" },
    { title: "Xero exports (configured)", description: "" },
    { title: "Custom theme (colours, fonts)", description: "" },
    { title: "Exports (csv files)", description: "" },
    { title: "Full system translation", description: "" },
  ],
  API: [
    { title: "API access", description: "" },
    { title: "Integrate TC into your website", description: "" },
    { title: "Zapier API access", description: "" },
    { title: "Custom workflows in Zapier", description: "" },
    { title: "General enquiry form", description: "" },
  ],
  Support: [
    { title: "System support (video call)", description: "" },
    { title: "Onboarding support", description: "" },
    { title: "System support (chat)", description: "" },
    { title: "AI chatbot", description: "" },
    { title: "Expert content", description: "" },
    { title: "Advanced support", description: "" },
  ],
  Integrations: [
    { title: "Online whiteboard", description: "" },
    { title: "Custom integrations", description: "" },
  ],
};
