// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordions: dynamic(() => import("./Accordions")),
  articles: dynamic(() => import("./Articles")),
  body_text: dynamic(() => import("./Body")),
  call_to_action: dynamic(() => import("./CallToAction")),
  faqs: dynamic(() => import("./Faqs")),
  hero: dynamic(() => import("./Hero")),
  logos: dynamic(() => import("./Logos")),
  stats: dynamic(() => import("./Stats")),
  team_list: dynamic(() => import("./TeamList")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_image_grid: dynamic(() => import("./AlternatingGrid")),
  youtube: dynamic(() => import("./Youtube")),
};
