export const schema = {
  "@id": "https://tutorcruncher.com/#webpage",
  "@context": "https://schema.org",
  "@type": "WebPage",
  headline:
    "Tutoring software,tutor management software,online tutoring software",
  url: "https://tutorcruncher.com/",
  description:
    "TutorCruncher is a comprehensive tutor management software, providing cloud-based solutions to streamline administrative tasks for tutoring companies. Launched in 2013, it features automation tools like CRM, job notifications, and lesson reminders to enhance efficiency and service quality. Developed with insights from the tutoring industry, TutorCrunchers experienced team ensures continuous improvement and client satisfaction.",
  keywords: [
    "Tutoring software",
    "tutor management software",
    "online tutoring software",
    "Online Classes",
    " Invoicing Online",
    " Features Billing",
    " Learning Paths",
    " Grading Learning",
    " Classes Automatic",
    " Automatic Grading",
    " online",
    " Online Tutoring",
    " Features",
    " tutors",
    " billing",
    " lessons",
    " Cookie",
    " software",
    " scheduling",
    " appointment scheduling",
    " business",
    " management software",
    " tutor management",
    " classes",
    " Paths",
    " Grading",
    " Tracks",
    " Cookie Consent",
    " Start free",
    " free trial",
    " Free",
    " Start",
    " trial",
    " Stripe integration",
    " TutorCruncher",
    " system",
    " Common Questions",
    " website",
    " Book",
    " time scheduling",
    " time",
    " book lessons",
    " invoicing system",
    " week",
    " Testimonials",
    " Increase",
    " Spend",
    " Engage",
    " Grow",
    " Stripe",
    " works brilliantly",
    " payment details",
    " fantastic addition",
    " Quickbooks",
    " log",
    " integrate",
    " Excel",
    " pay",
    " Absolutely",
    " Common",
    " Socket",
    " API",
    " completely transformed",
    " call",
    " profit",
    " simple",
    " payment",
    " details",
    " paid",
    " works",
    " fantastic",
    " addition",
    " forward",
    " setting",
    " customer support",
    " completely",
    " transformed",
    " support",
    " customer",
    " effortless",
    " update",
    " process",
    " enquiries",
    " extras",
    " list",
    " amount",
    " revenue",
    " features ",
  ],
  about: [
    {
      "@type": "Thing",
      name: "invoice",
      description:
        "commercial document issued by a seller to a buyer, relating to a sale transaction and indicating the products, quantities, and agreed prices for products or services the seller has provided the buyer",
      sameAs: [
        "https://en.wikipedia.org/wiki/Invoice",
        "https://www.wikidata.org/wiki/Q190581",
        "https://www.google.com/search?q=invoice&kgmid=/m/03g5n9",
      ],
    },
    {
      "@type": "Thing",
      name: "QuickBooks",
      description:
        "accounting software for small and medium-sized businesses developed by Intuit",
      sameAs: [
        "https://en.wikipedia.org/wiki/QuickBooks",
        "https://www.wikidata.org/wiki/Q7271951",
        "https://www.google.com/search?q=QuickBooks&kgmid=/m/05t4nn",
      ],
    },
    {
      "@type": "Thing",
      name: "Stripe",
      description: "Irish-American payment technology company",
      sameAs: [
        "https://en.wikipedia.org/wiki/Stripe,_Inc.",
        "https://www.wikidata.org/wiki/Q7624104",
        "https://www.google.com/search?q=Stripe&kgmid=/m/0h3qnb8",
      ],
    },
    {
      "@type": "Thing",
      name: "Intelligent tutoring system",
      description: "artificial intelligence system used for tutoring",
      sameAs: [
        "https://en.wikipedia.org/wiki/Intelligent_tutoring_system",
        "https://www.wikidata.org/wiki/Q3055492",
        "https://www.google.com/search?q=Intelligent+tutoring+system&kgmid=/m/09zttt",
      ],
    },
    {
      "@type": "Thing",
      name: "Educational software",
      description: "software used in education",
      sameAs: [
        "https://en.wikipedia.org/wiki/Educational_software",
        "https://www.wikidata.org/wiki/Q1074158",
        "https://www.google.com/search?q=Educational+software&kgmid=/m/01qk7d",
      ],
    },
    {
      "@type": "Thing",
      name: "Tutoring",
      description: "educator at home",
      sameAs: [
        "https://en.wikipedia.org/wiki/In-home_tutoring",
        "https://www.wikidata.org/wiki/Q656823",
        "https://www.google.com/search?q=Tutoring&kgmid=/m/02rft70",
      ],
    },
    {
      "@type": "Thing",
      name: "List of educational software",
      description: "Wikimedia list article",
      sameAs: [
        "https://en.wikipedia.org/wiki/List_of_educational_software",
        "https://www.wikidata.org/wiki/Q6618080",
        "https://www.google.com/search?q=List+of+educational+software&kgmid=/g/11csrsv9yz",
      ],
    },
    {
      "@type": "Thing",
      name: "Live online tutoring",
      description: "process of tutoring in an online environment",
      sameAs: [
        "https://en.wikipedia.org/wiki/Live_online_tutoring",
        "https://www.wikidata.org/wiki/Q22906544",
        "https://www.google.com/search?q=Live+online+tutoring&kgmid=/m/012sq8_m",
      ],
    },
  ],
  mentions: [
    {
      "@type": "Thing",
      name: "paper",
      description:
        "thin, flexible material mainly used for writing upon, printing upon, drawing or for packaging",
      sameAs: [
        "https://en.wikipedia.org/wiki/Paper",
        "https://www.wikidata.org/wiki/Q11472",
        "https://www.google.com/search?q=paper&kgmid=/m/0641k",
      ],
    },
    {
      "@type": "Thing",
      name: "invoice",
      description:
        "commercial document issued by a seller to a buyer, relating to a sale transaction and indicating the products, quantities, and agreed prices for products or services the seller has provided the buyer",
      sameAs: [
        "https://en.wikipedia.org/wiki/Invoice",
        "https://www.wikidata.org/wiki/Q190581",
        "https://www.google.com/search?q=invoice&kgmid=/m/03g5n9",
      ],
    },
    {
      "@type": "Thing",
      name: "QuickBooks",
      description:
        "accounting software for small and medium-sized businesses developed by Intuit",
      sameAs: [
        "https://en.wikipedia.org/wiki/QuickBooks",
        "https://www.wikidata.org/wiki/Q7271951",
        "https://www.google.com/search?q=QuickBooks&kgmid=/m/05t4nn",
      ],
    },
    {
      "@type": "Thing",
      name: "Stripe",
      description: "Irish-American payment technology company",
      sameAs: [
        "https://en.wikipedia.org/wiki/Stripe,_Inc.",
        "https://www.wikidata.org/wiki/Q7624104",
        "https://www.google.com/search?q=Stripe&kgmid=/m/0h3qnb8",
      ],
    },
    {
      "@type": "Thing",
      name: "European General Data Protection Regulation",
      description:
        "European Union regulation on the processing of personal data",
      sameAs: [
        "https://en.wikipedia.org/wiki/General_Data_Protection_Regulation",
        "https://www.wikidata.org/wiki/Q1172506",
        "https://www.google.com/search?q=European+General+Data+Protection+Regulation&kgmid=/m/0pk_7xs",
      ],
    },
    {
      "@type": "Thing",
      name: "electronic business",
      description:
        "the integrated execution of all automatable business processes of a company with the help of information and communication technology",
      sameAs: [
        "https://en.wikipedia.org/wiki/Electronic_business",
        "https://www.wikidata.org/wiki/Q734253",
        "https://www.google.com/search?q=electronic+business&kgmid=/m/01n697",
      ],
    },
    {
      "@type": "Thing",
      name: "whiteboard",
      description: "surface for nonpermanent markings",
      sameAs: [
        "https://en.wikipedia.org/wiki/Whiteboard",
        "https://www.wikidata.org/wiki/Q16354",
        "https://www.google.com/search?q=whiteboard&kgmid=/m/02d9qx",
      ],
    },
  ],
};
